module.exports={
    plugins:[
        require('postcss-uncss')({
            html:[
                './index.html'
            ]
        }),
        require('css-byebye')({
            html:[
                './index.html'
            ]
        })
    ]
}